# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

[env]
TERM = "alacritty"
COLORTERM = "truecolor"

[window]
decorations = "Full"

[font]
normal = { family = "PlemolJP Console NF" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 250
blink_timeout = 0

[keyboard]
bindings = [
    # { key = "Space", mods = "Control", chars = "\u0000" },
    # { key = "Slash", mods = "Control", chars = "\u001F" },
    { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~"},
    { key = "Tab", mods = "Shift|Control", chars = "\u001b[27;6;9~" },
    { key = "T", mods = "Shift|Control", chars = "\u001b[84;6u" },
    { key = "P", mods = "Shift|Control", chars = "\u001b[80;6u" },
    { key = "H", mods = "Shift|Control", chars = "\u001b[72;6u" },
    { key = "J", mods = "Shift|Control", chars = "\u001b[74;6u" },
	{ key = "K", mods = "Shift|Control", chars = "\u001b[75;6u" },
	{ key = "L", mods = "Shift|Control", chars = "\u001b[76;6u" },
]

[bell]
command = { program = "afplay", args = ["/System/Library/Sounds/Blow.aiff"] }
