name: ci
on:
  - push
jobs:
  apply:
    name: apply
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Apply dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
